# Generated by Django 4.1.1 on 2022-12-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='text',
            field=models.CharField(default='test_image', max_length=100),
        ),
    ]
